### ISSUE TITLE
画像認識部分作成

### ISSUE THREAD

**Issue by helloworld753315** [helloworld753315/ParkingManagement#8]

**Comment by helloworld753315** [comment]
作成したプロトタイプをラズパイ上で実行すると以下のエラーが、、、
手元の環境では動いていたので原因が特定できていない。

```
pi@raspberrypi:~/ParkingManagement $ python projects/recognition.py 
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(recognition.py:2346): Gdk-CRITICAL **: 20:21:27.123: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(recognition.py:2346): Gdk-CRITICAL **: 20:21:27.127: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Darknet format weights file loaded. projects/pytorch_yolov3/weights/yolov3.weights
Traceback (most recent call last):
  File "projects/recognition.py", line 86, in <module>
    detections = detector.detect_from_imgs(img)
  File "projects/pytorch_yolov3/yolov3/detector.py", line 101, in detect_from_imgs
    outputs = self.model(inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "projects/pytorch_yolov3/yolov3/models/yolov3.py", line 179, in forward
    x = module(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "projects/pytorch_yolov3/yolov3/models/yolo_layer.py", line 236, in forward
    return self.calc(output, labels)
  File "projects/pytorch_yolov3/yolov3/models/yolo_layer.py", line 135, in calc
    indexing="ij",
TypeError: meshgrid() got an unexpected keyword argument 'indexing'
```

**Comment by helloworld753315** [comment]
こちらは一時的に認識手法を変えることで解決。

**Comment by helloworld753315** [comment]
yolo-v3の学習済みモデルを使うと、何故か動かなかったので軽量化したものに置き換えてみる。
